# This file is automatically generated by https://github.com/nimbella/nimbella-cli/blob/master/release/homebrew.js
# Do not update this file directly;
# Please update the template instead:
# https://github.com/nimbella/nimbella-cli/blob/master/release/homebrew/templates/nimbella-node.rb
class NimbellaNode < Formula
  desc "NodeJS dependency for nimbella"
  homepage "https://docs.nimbella.com/command-summary"
  license "Apache-2.0"
  url "https://nodejs.org/download/release/v14.4.0/node-v14.4.0-darwin-x64.tar.xz"
  version "14.4.0"
  sha256 "98af3b9c9a179fbf731c06a9acedeb00c7fff8c8cb18cb48fa6f6cccd0013cd2"
  keg_only "nimbella-node is only used by Nimbella CLI (nimbella/brew/nimbella), which explicitly requires from Cellar"

  def install
    bin.install buildpath/"bin/node"
  end

  test do
    output = system bin/"node", "version"
    assert output.strip == "v#{version}"
  end
end

