on:
  push:
    tags: 'v*'

jobs:
  homebrew:
    name: Bump Homebrew formula
    runs-on: ubuntu-latest
    steps:
      - uses: mislav/bump-homebrew-formula-action@v1
        if: "!contains(github.ref, '-')" # skip prereleases
        with:
          formula-name: nimbella-cli.rb
          homebrew-tap: nimbella/homebrew-brew
          base-branch: master
          download-url: https://apigcp.nimbella.io/downloads/nim/nim-v1.13.0/nim-v1.13.0-linux-x64.tar.gz
          commit-message: ${{formulaName}} ${{version}}
        env:
          COMMITTER_TOKEN: ${{ secrets.COMMITTER_TOKEN }}
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
